name: Update File

on:
  workflow_dispatch:
    inputs:
      filePath:
        description: 'File path to update'
        required: true
      newContent:
        description: 'New content for the file'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update file content
      id: update_file
      run: |
        echo "${{ github.event.inputs.newContent }}" > ${{ github.event.inputs.filePath }}
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ github.event.inputs.filePath }}
        git commit -m "Update ${{ github.event.inputs.filePath }}"
        git push

    - name: Output result
      run: echo "File updated successfully"
